<?php
return array(
    'sds' => array(
        'identity' => array(
            'enableAccessControl' => false,
            'identityControllerOptions' => [
                'documentManager' => 'doctrine.documentmanager.odm_default',
                'documentValidator' => 'Sds\DoctrineExtensions\DocumentValidator',
                'serializer' => 'Sds\DoctrineExtensions\Serializer',
                'identityClass' => 'Sds\IdentityModule\DataModel\Identity',
                'mailTransport' => 'sds.mailTransport.smtp',
                'mailFrom' => 'sds@identitymodule.dummy',
                'forgotCredentialLink' => 'http://localhost/ZendSkeletonApplication/forgotCredential?name=[name]&forgotCredentialCode=[code]',
                'forgotCredentialExpiry' => 4*60*60, //time in seconds
                'forgotCredentialEmailSubject' => 'forgot password',
                'limit' => 30 //max number of records returned from getList
            ],
            'emailCryptKey' => 'change this key phrase in your own app',
        ),
        'doctrineExtensions' => array(
            'extensionConfigs' => array(
                'Sds\DoctrineExtensions\Readonly' => null,
                'Sds\DoctrineExtensions\Serializer' => null,
                'Sds\DoctrineExtensions\Validator' => ['validateOnFlush' => false],
                'Sds\DoctrineExtensions\Crypt' => null,
                'Sds\DoctrineExtensions\Dojo' => array(
                    'destPaths' => array(
                        'all' => array(
                            'filter' => 'Sds\IdentityModule',
                            'path' => 'vendor/dojo'
                        ),
                    ),
                ),
            ),
        ),
        'accessControl' => array(
            'controllers' => array(
                'identity' => array(
                    'actions' => array(
                        'forgotCredentialPart1' => array(
                            'roles' => array(
                                \Sds\Common\AccessControl\Constant\Role::guest
                            ),
                        ),
                    ),
                ),
                'identityRest' => array(
                    'actions' => array(
                        'create' => array(
                            'roles' => array(
                                \Sds\Common\AccessControl\Constant\Role::guest
                            ),
                        ),
                        'read' => array(
                            'roles' => array(
                                \Sds\Common\AccessControl\Constant\Role::guest
                            ),
                        ),
                        'update' => array(
                            'roles' => array(
                                \Sds\Common\AccessControl\Constant\Role::guest
                            ),
                        ),
                        'delete' => array(
                            'roles' => array(
                                \Sds\Common\AccessControl\Constant\Role::guest
                            ),
                        ),
                    ),
                ),
            ),
        ),

        //The path to place smd generated by the generate-json-rpc-smd command line tool
        'jsonRpcSmdGenerator' => array(
            'sds.identity' => array(
                'path' => 'vendor/dojo/Sds/IdentityModule/Smd.js',
                'format' => 'dojo', // dojo | json
                'target' => 'http://localhost/ZendSkeletonApplication/identity', //Override this target in your own config
            ),
        ),
    ),

    'router' => array(
        'routes' => array(
            'sds.identity' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route'    => '/identity',
                    'defaults' => array(
                        'controller' => 'sds.identity',
                    ),
                ),
            ),
            'sds.identity.forgotCredential' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route'    => '/forgotCredential',
                    'defaults' => array(
                        'controller' => 'sds.identity.forgotCredential',
                        'action' => 'forgotCredential'
                    ),
                ),
            ),
            'sds.identityRest' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route'    => '/identity/rest',
                    'defaults' => array(
                        'controller' => 'Sds/IdentityModule/Controller/IdentityRestController',
                    ),
                ),
            ),
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'sds.identity.forgotCredential' => 'Sds\IdentityModule\Controller\RecoverPasswordController'
        ),
        'factories' => array(
            'sds.identity' => 'Sds\IdentityModule\Service\IdentityControllerFactory',
            'Sds/IdentityModule/Controller/IdentityRestController' => 'Sds\IdentityModule\Service\IdentityRestControllerFactory'
        ),
    ),

    'doctrine' => array(
        'driver' => array(
            'odm_default' => array(
                'drivers' => array(
                    'Sds\IdentityModule\DataModel' => 'sds.identity'
                ),
            ),
            'sds.identity' => array(
                'class' => 'Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver',
                'paths' => array(
                    'vendor/superdweebie/identity-module/src/Sds/IdentityModule/DataModel'
                ),
            ),
        ),
    ),

    'service_manager' => array(
        'factories' => array(
            'sds.mailTransport.stmp' => function(){
                return new \Zend\Mail\Transport\Smtp([
                    //Add your mail settings here
                ]);
            },
        ),
    ),

    'view_manager' => array(
        'template_map'             => array(
            'email/recover-password' => __DIR__ . '/../view/email/recover-password.phtml',
            'sds/recover-password/recover-password' => __DIR__ . '/../view/sds/recover-password/recover-password.phtml',
        ),
        'template_path_stack' => array(
            __DIR__ . '/../view',
        )
    )
);
